orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 158175188896.dkr.ecr.us-east-2.amazonaws.com/docker-repo
          aws-access-key-id: AKIASJU7Z26QN5C2JYEE
          aws-secret-access-key: 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
          context: myContext
          create-repo: true
          dockerfile: DockerFile
          path: .
          profile-name: myProfileName
          region: us-east-2
          repo: docker-repo
          tag: jeje
