orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: accountUrl
          aws-access-key-id: AKIASJU7Z26QN5C2JYEE
          aws-secret-access-key: awsSecretAccessKey
          context: CI
          create-repo: true
          dockerfile: DockerFile
          path: .
          profile-name: CircleCIGroup
          region: region
          repo: docker-repo
          tag: jeje
